# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Slack Stream Action'
description: 'Github Action to provide a single message that gets updated with the github workflow run status'
author: 'ksmithut'
branding:
  icon: alert-circle
  color: red
inputs:
  slack-bot-token:
    description: The slack app bot token to use when making API calls against the Slack API
    required: false
  slack-channel-id:
    description: The channel id of the channel to post messages to
    required: false
  slack-ts:
    description: The slack ts from a previous message. Required in all steps but the first one
    required: false
  github-token:
    description: Token used to get the workflow status
    required: true
    default: ${{ github.token }}
outputs:
  slack-ts:
    description: The slack ts used from previous jobs
runs:
  using: 'node16'
  pre: 'dist/pre.js'
  main: 'dist/main.js'
  post: 'dist/post.js'
