name: Test
on:
  push:
    branches:
      - main

env:
  SLACK_STREAM: false

jobs:
  test:
    name: Run with node ${{ matrix.version }}
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello'
      - run: sleep 5
