name: Test
on:
  push:
    branches:
      - master
env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
jobs:
  test:
    name: First comes the tests
    outputs:
      slack-ts: ${{ steps.slack.outputs.slack-ts }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: slack
        uses: '.'
      - run: echo 'hello'
